### PR TITLE
Added setup.sh

### PR DESCRIPTION
**Pull request by SteliosMalamas**
- Created setup.sh to install dependencies automatically and compile
- Updated README.md

### CODE REVIEW

**Review by TheRealOne78 — COMMENTED** [review]
Wow nice, someone is actually contributing for XAWP. Thank you :)
And it's actually a nice idea I can't believe I didn't think of. 
One mention, I kind of want it to have as much as possible package installer, so I will have to change setup.sh a little.

PR will be probably stalled for a few more days because I got into a little accident. That's the reason I didn't commit to XAWP for a while.

Thank you for your contribution, looking forward to push is as soon as possible :)

**Comment by SteliosMalamas** [comment]
Yeah of course. Take your time and get well soon :)

**Comment by TheRealOne78** [comment]
Converted to draft since I want to make some little changes

**Comment by TheRealOne78** [comment]
It seems like github broke and your repository doesn't exist anymore, I will just merge it and modify it later

**Comment by SteliosMalamas** [comment]
As of now running `setup.sh` gives the following errors:
```
setup.sh: 4: deb-dependencies=gcc make libimlib2-dev libx11-dev libconfig-dev: not found
setup.sh: 7: [[: not found
setup.sh: 54: Syntax error: "(" unexpected (expecting "fi")
```

**Comment by TheRealOne78** [comment]
Resolved! :+1:

**Comment by SteliosMalamas** [comment]
I still get `setup.sh: 7: [[: not found` as well as `make: invalid option -- '4'`. It also doesn't seem to detect when I'm not running it as root. This is the full output when I run it as root:

```
setup.sh: 7: [[: not found
apt-get detected
Installing dependencies...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:9.3.0-1ubuntu2).
make is already the newest version (4.2.1-1.2).
libconfig-dev is already the newest version (1.5-0.4build1).
libx11-dev is already the newest version (2:1.6.9-2ubuntu1.2).
libimlib2-dev is already the newest version (1.6.1-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
make: invalid option -- '4'
Usage: make [options] [target] ...
Options:
  -b, -m                      Ignored for compatibility.
  -B, --always-make           Unconditionally make all targets.
  -C DIRECTORY, --directory=DIRECTORY
                              Change to DIRECTORY before doing anything.
  -d                          Print lots of debugging information.
  --debug[=FLAGS]             Print various types of debugging information.
  -e, --environment-overrides
                              Environment variables override makefiles.
  --eval=STRING               Evaluate STRING as a makefile statement.
  -f FILE, --file=FILE, --makefile=FILE
                              Read FILE as a makefile.
  -h, --help                  Print this message and exit.
  -i, --ignore-errors         Ignore errors from recipes.
  -I DIRECTORY, --include-dir=DIRECTORY
                              Search DIRECTORY for included makefiles.
  -j [N], --jobs[=N]          Allow N jobs at once; infinite jobs with no arg.
  -k, --keep-going            Keep going when some targets can't be made.
  -l [N], --load-average[=N], --max-load[=N]
                              Don't start multiple jobs unless load is below N.
  -L, --check-symlink-times   Use the latest mtime between symlinks and target.
  -n, --just-print, --dry-run, --recon
                              Don't actually run any recipe; just print them.
  -o FILE, --old-file=FILE, --assume-old=FILE
                              Consider FILE to be very old and don't remake it.
  -O[TYPE], --output-sync[=TYPE]
                              Synchronize output of parallel jobs by TYPE.
  -p, --print-data-base       Print make's internal database.
  -q, --question              Run no recipe; exit status says if up to date.
  -r, --no-builtin-rules      Disable the built-in implicit rules.
  -R, --no-builtin-variables  Disable the built-in variable settings.
  -s, --silent, --quiet       Don't echo recipes.
  -S, --no-keep-going, --stop
                              Turns off -k.
  -t, --touch                 Touch targets instead of remaking them.
  --trace                     Print tracing information.
  -v, --version               Print the version number of make and exit.
  -w, --print-directory       Print the current directory.
  --no-print-directory        Turn off -w, even if it was turned on implicitly.
  -W FILE, --what-if=FILE, --new-file=FILE, --assume-new=FILE
                              Consider FILE to be infinitely new.
  --warn-undefined-variables  Warn when an undefined variable is referenced.

This program built for x86_64-pc-linux-gnu
Report bugs to <bug-make@gnu.org>
Compiled! Please run "make install" as super user to install in your system.

```

**Comment by TheRealOne78** [comment]
oh I see why, modifying in a bit

**Comment by TheRealOne78** [comment]
modified, this time I took a liik in the workflow and everythign seems to be fine now: https://github.com/TheRealOne78/XAWP/runs/7598133049?check_suite_focus=true
Thanks

**Comment by SteliosMalamas** [comment]
Yep, it works now!

**Pull request merged**
